[package]
name = "ast"
version = "0.1.0"
edition = "2021"


[build-dependencies]
lalrpop = "0.21.0"

[dependencies]
codespan = "0.11.1"
lalrpop-util = "0.21.0"
nom = "7.1.3"
unescape = "0.1.0"





[profile.release]
debug = true
